name: Update Table

on:
  push:
    branches:
      - your-sub-branch
  pull_request:
    branches:
      - your-sub-branch

jobs:
  generate-table:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Generate Table
        run: |
          python rfcfg_profiles/create.py --config rfcfg_profiles/config.csv --print > generated_table.txt
      
      - name: Update Confluence Page
        env:
          CONFLUENCE_URL: ${{ secrets.CONFLUENCE_URL }}
          CONFLUENCE_USERNAME: ${{ secrets.CONFLUENCE_USERNAME }}
          CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
          CONFLUENCE_PAGE_ID: ${{ secrets.CONFLUENCE_PAGE_ID }}
        run: |
          python scripts/update_confluence.py generated_table.txt
